version: "3"

services:
  myapp1:
    build: .
    command: ["foreground"]
    ports:
      - "4000:4000"
    environment:
      - APP_IP_ADDRESS=172.16.238.10
    networks:
      app_network:
        ipv4_address: 172.16.238.10
  myapp2:
    build: .
    command: ["foreground"]
    ports:
      - "4001:4000"
    environment:
      - APP_IP_ADDRESS=172.16.238.20
    networks:
      app_network:
        ipv4_address: 172.16.238.20
  myapp3:
    build: .
    command: ["foreground"]
    ports:
      - "4002:4000"
    environment:
      - APP_IP_ADDRESS=172.16.238.30
    networks:
      app_network:
        ipv4_address: 172.16.238.30
networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
